# Generated by Django 4.0.5 on 2022-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('flights', '0001_initial'), ('flights', '0002_flight_city_flight_company_flight_country_and_more'), ('flights', '0003_rename_flight_flightmodel'), ('flights', '0004_remove_flightmodel_id_alter_flightmodel_date'), ('flights', '0005_alter_flightmodel_date'), ('flights', '0006_flightmodel_id_alter_flightmodel_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('city', models.CharField(default='default', max_length=100)),
                ('company', models.CharField(default='default', max_length=100)),
                ('country', models.CharField(default='default', max_length=100)),
                ('date', models.DateField(default='default', max_length=100)),
                ('status', models.CharField(default='default', max_length=100)),
                ('id', models.UUIDField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
