# Generated by Django 4.0.5 on 2022-07-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='city',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='company',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='country',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
