# Generated by Django 4.0.5 on 2022-07-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_city_flight_company_flight_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='FlightModel',
        ),
    ]
