# Generated by Django 4.0.5 on 2022-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flight_flightmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='date',
            field=models.CharField(default='default', max_length=100, primary_key=True, serialize=False),
        ),
    ]
