# Generated by Django 4.0.5 on 2022-07-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_flightmodel_id_alter_flightmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='date',
            field=models.DateField(default='default', max_length=100, primary_key=True, serialize=False),
        ),
    ]
