# Generated by Django 4.0.5 on 2022-07-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_flightmodel_id_alter_flightmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
