# Generated by Django 4.0.5 on 2022-07-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flightmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
