# Generated by Django 4.0.5 on 2022-07-02 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_flightmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
