# Generated by Django 4.0.5 on 2022-07-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20220702_0521'),
    ]

    operations = [
    ]
