# Generated by Django 4.0.5 on 2022-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_auto_20220702_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
