# Generated by Django 4.0.5 on 2022-07-02 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_flightmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
